---
  all:
    #single:
    #  children:
    #    ansibletest04:
    hosts:
      ansibletest03:
        ansible_host: 10.250.4.203
        iface: ens161
        build: cache_rhel8
        ksurl: https://raw.githubusercontent.com/lspiehler/ansible_vmware_build/master/kickstarts/cache_rhel8.ks
        extra_kernel_args: inst.noverifyssl
        disks:
          - size_gb: 120
            type: thick
            datastore: ESX_NFS_N1_03
            controller_number: 0
            unit_number: 0
            controller_type: paravirtual
          - size_gb: 20
            type: thick
            datastore: ESX_NFS_N1_03
            controller_number: 0
            unit_number: 1
            controller_type: paravirtual
          - size_gb: 30
            type: thick
            datastore: ESX_NFS_N1_03
            controller_number: 1
            unit_number: 0
            controller_type: paravirtual
          - size_gb: 146
            type: thick
            datastore: ESX_NFS_N1_03
            controller_number: 2
            unit_number: 0
            controller_type: paravirtual
          - size_gb: 60
            type: thick
            datastore: ESX_NFS_N1_03
            controller_number: 3
            unit_number: 0
            controller_type: paravirtual
      ansibletest04:
        ansible_host: 10.250.4.204
        num_cpus: 2
        memory_mb: 4096
        build: cache_rhel8
        ksurl: https://raw.githubusercontent.com/lspiehler/ansible_vmware_build/master/kickstarts/rhel8.ks
        extra_kernel_args: inst.noverifyssl
        disks:
          - size_gb: 25
            type: thick
            datastore: ESX_NFS_N1_03
            controller_number: 0
            unit_number: 0
            controller_type: paravirtual
      #ansibletest05:
      #  ansible_host: 10.250.4.205
      #ansibletest06:
      #  ansible_host: 10.250.4.206
      #ansibletest07:
      #  ansible_host: 10.250.4.207
    vars:
      memory_mb: 2048
      num_cpus: 1
      netmask: 255.255.255.0
      gateway: 10.250.4.1
      dns1: 10.250.4.10
      dns2: 10.250.4.11
      device_type: vmxnet3
      iface: ens192
      iso_path: "[ESX_NFS_N1_01] ISO/rhel-8.3-x86_64-dvd.iso"
      vcenter_cluster: TI-VSI
      vcenter_datacenter: Touro
      vcenter_network: VM Network VLAN 254
      vcenter_guestid: rhel7_64Guest
      vcenter_folder: /
      validate_certs: no
...
