---
  all:
    hosts:
      ansibletest03:
        ansible_host: 10.250.4.203
      ansibletest04:
        ansible_host: 10.250.4.204
      ansibletest05:
        ansible_host: 10.250.4.205
      #ansibletest06:
        #ansible_host: 10.250.4.206
      #ansibletest07:
        #ansible_host: 10.250.4.207
    vars:
      memory_mb: 2048
      num_cpus: 1
      netmask: 255.255.255.0
      gateway: 10.250.4.1
      dns1: 10.250.4.10
      dns2: 10.250.4.11
      device_type: vmxnet3
      iface: ens160
      size_gb: 25
      type: thin
      iso_path: "[ESX_NFS_N1_01] ISO/rhel-8.3-x86_64-dvd.iso"
      scsi: lsilogic
      ksurl: https://raw.githubusercontent.com/lspiehler/ansible_vmware_build/master/kickstarts/rhel8.ks
      extra_kernel_args: inst.noverifyssl
      vcenter_cluster: TI-VSI
      vcenter_datacenter: Touro
      vcenter_datastore: ESX_NFS_N2_03
      vcenter_network: VM Network VLAN 254
      vcenter_guestid: rhel7_64Guest
      vcenter_folder: /
      validate_certs: no
...
